exports.loadCss = require('./css')
exports.loadJavaScript = require('./javascript')
exports.loadImages = require('./images')
exports.loadSvg = require('./svg')
exports.setupHtml =  require('./assets')
